FROM golang:1.21-alpine

# Install tools
RUN apk add --no-cache git build-base

# Install a compatible goose version (e.g. v3.20.0 works with Go 1.21)
RUN go install github.com/pressly/goose/v3/cmd/goose@v3.20.0

WORKDIR /app
COPY migrations /app/migrations

# ENTRYPOINT ["/go/bin/goose"]
ENTRYPOINT sh -c "/go/bin/goose -dir /app/migrations postgres \"postgres://${APP_DB_USERNAME}:${APP_DB_PASSWORD}@${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_DATABASE}?sslmode=disable\" up"
